export const GET_BRAND_REQUEST = "GET_BRAND_REQUEST";
export const GET_BRAND_SUCCESS = "GET_BRAND_SUCCESS";
export const GET_BRAND_FAILD = "GET_BRAND_FAILD";

export const CREATE_BRAND_SUCCESS = "CREATE_BRAND_SUCCESS";
export const CREATE_BRAND_FAILD = "CREATE_BRAND_FAILD";

export const DELATE_BRAND_SUCCESS = "DELATE_BRAND_SUCCESS";
export const DELATE_BRAND_FAILD = "DELATE_BRAND_FAILD";
